sh build.sh AIRBOTF4
sh build.sh AIRHEROF3
sh build.sh AIRHEROF3_QUAD
sh build.sh ALIENFLIGHTF3
sh build.sh ALIENFLIGHTF4
sh build.sh ALIENFLIGHTNGF7
sh build.sh ANYFC
sh build.sh ANYFCF7
sh build.sh ANYFCF7_EXTERNAL_BARO
sh build.sh ANYFCM7
sh build.sh ASGARD32F4
sh build.sh ASGARD32F7
sh build.sh BEEROTORF4
sh build.sh BETAFLIGHTF3
sh build.sh BETAFLIGHTF4
sh build.sh BLUEJAYF4
sh build.sh CHEBUZZF3
sh build.sh CLRACINGF4AIR
sh build.sh CLRACINGF4AIRV2
sh build.sh CLRACINGF4AIRV3
sh build.sh COLIBRI
sh build.sh COLIBRI_RACE
sh build.sh DALRCF405
sh build.sh DALRCF722DUAL
sh build.sh DYSF4PRO
sh build.sh DYSF4PROV2
sh build.sh F4BY
sh build.sh FALCORE
sh build.sh FF_F35_LIGHTNING
sh build.sh FF_FORTINIF4
sh build.sh FF_PIKOF4
sh build.sh FF_PIKOF4OSD
sh build.sh FIREWORKSV2
sh build.sh FISHDRONEF4
sh build.sh FOXEERF405
sh build.sh FOXEERF722DUAL
sh build.sh FRSKYF3
sh build.sh FRSKYF4
sh build.sh FURYF3
sh build.sh FURYF3_SPIFLASH
sh build.sh KAKUTEF4
sh build.sh KAKUTEF4V2
sh build.sh KAKUTEF7
sh build.sh KFC32F3_INAV
sh build.sh KISSFC
sh build.sh KROOZX
sh build.sh LUX_RACE
sh build.sh MATEKF405
sh build.sh MATEKF405OSD
sh build.sh MATEKF405SE
sh build.sh MATEKF405_SERVOS6
sh build.sh MATEKF411
sh build.sh MATEKF411_RSSI
sh build.sh MATEKF411_SFTSRL2
sh build.sh MATEKF722
sh build.sh MATEKF722MINI
sh build.sh MATEKF722SE
sh build.sh MATEKF722_HEXSERVO
sh build.sh MOTOLAB
sh build.sh OMNIBUS
sh build.sh OMNIBUSF4
sh build.sh OMNIBUSF4PRO
sh build.sh OMNIBUSF4PRO_LEDSTRIPM5
sh build.sh OMNIBUSF4V3
sh build.sh OMNIBUSF7
sh build.sh OMNIBUSF7NXT
sh build.sh OMNIBUSF7V2
sh build.sh PIKOBLX
sh build.sh PIXRACER
sh build.sh QUANTON
sh build.sh RADIX
sh build.sh RCEXPLORERF3
sh build.sh REVO
sh build.sh RMDO
sh build.sh SPARKY
sh build.sh SPARKY2
sh build.sh SPEEDYBEEF4
sh build.sh SPRACINGF3
sh build.sh SPRACINGF3EVO
sh build.sh SPRACINGF3EVO_1SS
sh build.sh SPRACINGF3MINI
sh build.sh SPRACINGF3NEO
sh build.sh SPRACINGF4EVO
sh build.sh SPRACINGF7DUAL
sh build.sh STM32F3DISCOVERY
sh build.sh YUPIF4
sh build.sh YUPIF4MINI
sh build.sh YUPIF4R2
sh build.sh YUPIF7
